- hosts: localhost
  vars_files:
    - .local.vars.yml

  vars:
    work_dir: "{{ playbook_dir }}/work"

  roles:
    - role: kameshsampath.xks.civo
      tags:
        - cloud
        - civo
    - role: kameshsampath.xks.azure
      tags:
        - cloud
        - azure
    - role: kameshsampath.xks.google
      tags:
        - cloud
        - gcp
      environment:
        GOOGLE_APPLICATION_CREDENTIALS: "{{ gcp_cred_file  }}"
    - role: kameshsampath.xks.amazon
      tags:
        - cloud
        - aws

  tasks:
    - name: "Create Work Directories"
      local_action:
        module: ansible.builtin.file
        dest: "{{ work_dir }}/.kube"
        mode: 0700
        state: directory
      tags:
        - work
        - base
    - name: "Merge Kubconfig"
      set_fact:
        kubeconfig: "{{ lookup('fileglob', work_dir +'/.kube/*.kubeconfig') | regex_replace(',',':') }}"
      tags:
        - work
        - base

    - name: "Debug::Available Kubeconfigs"
      debug:
        var: kubeconfig
      tags:
        - work
        - base

    - name: "Merge and Flatten Kubeconfig"
      local_action:
        module: ansible.builtin.command
        argv:
          - kubectl
          - config
          - view
          - --flatten
      register: merged_kubeconfig
      environment:
        KUBECONFIG: "{{ kubeconfig  }}"
      tags:
        - work
        - base

    - name: "Save work Kubeconfig"
      local_action:
        module: ansible.builtin.copy
        dest: "{{ work_dir }}/.kube/config"
        content: "{{ merged_kubeconfig.stdout | from_yaml | to_nice_yaml(indent=2) }}"
      tags:
        - work
        - base
