---
collections:
  - name: ansible.posix
    version: '1.4.0'
  - name: community.general
    version: '3.5.0'
  - name: kubernetes.core
    version: '2.3.2'
  - name: google.cloud 
    version: '1.0.2'
  - name: amazon.aws
    version: '3.4.0'
  - name: community.aws
    version: '3.5.0'
  - name: azure.azcollection
    version: '1.13.0'
